/**
 * Assembles AI-generated content into structured markdown documents.
 */

import type { CobolStructure, CobolProject } from '@/types/cobol';
import type { KnowledgeBase, ProjectStatistics } from '@/types/documentation';
import type { DependencyGraph } from '@/lib/cobol/call-chain';
import { generateSystemDependencyDiagram } from './mermaid';

export function generateProjectOverview(
  project: CobolProject,
  graph: DependencyGraph,
): string {
  const stats = computeStatistics(project);

  return `# ${project.name} — COBOL Codebase Documentation

> Generated by [Assay](https://assay.software) on ${new Date().toISOString().split('T')[0]}

## System Overview

| Metric | Value |
|--------|-------|
| Total Programs | ${stats.totalPrograms} |
| Total Copybooks | ${stats.totalCopybooks} |
| Total Lines of Code | ${stats.totalLines.toLocaleString()} |
| Code Lines (non-comment, non-blank) | ${stats.totalCodeLines.toLocaleString()} |
| Comment Lines | ${stats.totalCommentLines.toLocaleString()} |

## System Dependency Map

\`\`\`mermaid
${generateSystemDependencyDiagram(graph)}
\`\`\`

${graph.unresolvedCalls.length > 0 ? `### Unresolved External Calls\nThe following programs are called but not found in this codebase:\n${graph.unresolvedCalls.map((c) => `- \`${c}\``).join('\n')}\n` : ''}

${graph.unresolvedCopies.length > 0 ? `### Unresolved Copybooks\nThe following copybooks are referenced but not found:\n${graph.unresolvedCopies.map((c) => `- \`${c}\``).join('\n')}\n` : ''}

${graph.orphanPrograms.length > 0 ? `### Potentially Orphaned Programs\nThese programs exist but are never called by other programs in this codebase:\n${graph.orphanPrograms.map((p) => `- \`${p}\``).join('\n')}\n` : ''}

## Programs

| Program ID | File | Lines | Paragraphs | Calls | Copies |
|------------|------|-------|------------|-------|--------|
${project.programs
  .map(
    (p) =>
      `| [${p.programId}](programs/${p.programId}/overview.md) | ${p.file.filename} | ${p.file.lineCount} | ${p.metrics.paragraphCount} | ${p.metrics.callCount} | ${p.metrics.copyCount} |`,
  )
  .join('\n')}

## Copybooks

| Name | File | Lines |
|------|------|-------|
${project.copybooks
  .map(
    (c) =>
      `| ${c.filename.replace(/\.(cpy|copy)$/i, '')} | ${c.filename} | ${c.lineCount} |`,
  )
  .join('\n')}
`;
}

export function generateProgramDocument(
  program: CobolStructure,
  aiOverview: string,
  aiBusinessRules: string,
  aiDeadCode: string,
  aiDataFlow: string,
): string {
  return `# ${program.programId}

> File: \`${program.file.filename}\` | Lines: ${program.file.lineCount} | Generated by Assay

## Quick Stats

| Metric | Value |
|--------|-------|
| Total Lines | ${program.metrics.totalLines} |
| Code Lines | ${program.metrics.codeLines} |
| Comment Lines | ${program.metrics.commentLines} |
| Paragraphs | ${program.metrics.paragraphCount} |
| CALL Statements | ${program.metrics.callCount} |
| COPY Statements | ${program.metrics.copyCount} |
| Data Items | ${program.metrics.dataItemCount} |
| Max Nesting Depth | ${program.metrics.maxNestingDepth} |

---

${aiOverview}

---

## Business Rules

${aiBusinessRules}

---

## Dead Code Analysis

${aiDeadCode}

---

## Data Flow

${aiDataFlow}
`;
}

export function generateIndexDocument(project: CobolProject): string {
  return `# ${project.name} — Documentation Index

## Quick Navigation

- [System Overview](overview.md)
- [System Dependency Map](overview.md#system-dependency-map)

## Programs (${project.programs.length})

${project.programs
  .map(
    (p) =>
      `- [${p.programId}](programs/${p.programId}/overview.md) — ${p.file.filename} (${p.file.lineCount} lines)`,
  )
  .join('\n')}

## Copybooks (${project.copybooks.length})

${project.copybooks
  .map(
    (c) =>
      `- [${c.filename.replace(/\.(cpy|copy)$/i, '')}](copybooks/${c.filename.replace(/\.(cpy|copy)$/i, '')}.md) — ${c.lineCount} lines`,
  )
  .join('\n')}
`;
}

function computeStatistics(project: CobolProject): ProjectStatistics {
  let totalCodeLines = 0;
  let totalCommentLines = 0;

  for (const prog of project.programs) {
    totalCodeLines += prog.metrics.codeLines;
    totalCommentLines += prog.metrics.commentLines;
  }

  return {
    totalPrograms: project.totalPrograms,
    totalCopybooks: project.totalCopybooks,
    totalLines: project.totalLines,
    totalCodeLines,
    totalCommentLines,
    totalBusinessRules: 0,
    totalDeadCodeItems: 0,
    estimatedDeadCodePercentage: 0,
  };
}
